repos:
  - repo: local
    hooks:
      - id: black-autofix
        name: black (autofix and stage)
        entry: bash -c 'black --line-length=79 "$@" && git add "$@"' --
        language: system
        types: [python]
